=== oguzdgd/movie/schemas/movie_schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="movie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="xs:string"/>
                <xs:element name="year" type="xs:gYear" minOccurs="0"/>
                <xs:element name="director" type="xs:string" minOccurs="0"/>
                <xs:element name="genres" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="genre" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="actors" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actor" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="plot" type="xs:string" minOccurs="0"/>
                <xs:element name="posterUrl" type="xs:anyURI" minOccurs="0"/>
                <xs:element name="rating" minOccurs="0">
                    <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                            <xs:minInclusive value="0"/>
                            <xs:maxInclusive value="10"/>
                            <xs:fractionDigits value="1"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="id" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== oguzdgd/movie/data/movies/parasite_mov003.xml
<?xml version="1.0" encoding="UTF-8"?>
<movie id="mov003" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../schemas/movie_schema.xsd">
    <title>Parasite</title>
    <year>2019</year>
    <director>Bong Joon Ho</director>
    <genres>
        <genre>Thriller</genre>
        <genre>Comedy</genre>
        <genre>Drama</genre>
    </genres>
    <actors>
        <actor>Song Kang-ho</actor>
        <actor>Lee Sun-kyun</actor>
        <actor>Cho Yeo-jeong</actor>
    </actors>
    <plot><![CDATA[Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.]]></plot>
    <posterUrl>https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg</posterUrl>
    <rating>8.5</rating>
</movie>

=== oguzdgd/movie/data/movies/inception_mov001.xml
<?xml version="1.0" encoding="UTF-8"?>
<movie id="mov001" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../schemas/movie_schema.xsd">
    <title>Inception</title>
    <year>2010</year>
    <director>Christopher Nolan</director>
    <genres>
        <genre>Sci-Fi</genre>
        <genre>Action</genre>
        <genre>Thriller</genre>
    </genres>
    <actors>
        <actor>Leonardo DiCaprio</actor>
        <actor>Joseph Gordon-Levitt</actor>
        <actor>Elliot Page</actor>
    </actors>
    <plot><![CDATA[A thief who steals information by entering people's dreams is offered a chance to have his criminal history erased as payment for a task considered to be impossible: "inception", the implantation of another person's idea into a target's subconscious.]]></plot>
    <posterUrl>https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg</posterUrl>
    <rating>8.8</rating>
</movie>

=== oguzdgd/movie/data/movies/interstellar_mov002.xml
<?xml version="1.0" encoding="UTF-8"?>
<movie id="mov002" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="../../schemas/movie_schema.xsd">
    <title>Interstellar</title>
    <year>2014</year>
    <director>Christopher Nolan</director>
    <genres>
        <genre>Sci-Fi</genre>
        <genre>Drama</genre>
        <genre>Adventure</genre>
    </genres>
    <actors>
        <actor>Matthew McConaughey</actor>
        <actor>Anne Hathaway</actor>
        <actor>Jessica Chastain</actor>
    </actors>
    <plot><![CDATA[A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.]]></plot>
    <posterUrl>https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg</posterUrl>
    <rating>8.7</rating>
</movie>
